name: deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2) QEMU/Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) 이미지 빌드 & 푸시
      - name: Build & Push Spring Boot Image
        uses: docker/build-push-action@v6
        with:
          context: ./springboot-app3
          file: ./springboot-app3/Dockerfile
          push: true
          tags: jungwonalicia/springboot3-web3:latest
          platforms: linux/amd64

      # 5) AWS 자격증명 (Access Key 방식)
        - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-northeast-2

            - name: Deploy via SSM
              run: |
                REMOTE_SCRIPT=$(cat <<'EOS'
                set -euo pipefail
                cd ~/springboot3
                docker compose pull
                docker compose up -d
                docker compose ps
                EOS
                )
      
                jq -n --arg s "$REMOTE_SCRIPT" '{commands: [$s]}' > /tmp/ssm-params.json
      
                CMD_ID=$(aws ssm send-command \
                  --region ap-northeast-2 \
                  --document-name "AWS-RunShellScript" \
                  --targets "Key=instanceIds,Values=i-xxxxxxxxxxxxx" \
                  --parameters file:///tmp/ssm-params.json \
                  --query "Command.CommandId" \
                  --output text)
      
                echo "SSM CommandId: $CMD_ID"
                aws ssm wait command-executed --region ap-northeast-2 --command-id "$CMD_ID" --targets "Key=instanceIds,Values=i-xxxxxxxxxxxxx"